server:
  port: 8081

resources:
  mp3:
    pathPatterns: /2017/mp3/**
    resourceLocations: file:/Users/cdfive/learning/mp3/

spring:
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 20