spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  profiles:
    active: dev

resources:
  static:
    pathPatterns: /static/**
    resourceLocations: classpath:/static/