server:
  port: 9090

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: cdfive-api
          uri: http://localhost:7070
          predicates:
            - Path=/api/v1/**
        - id: httpbin_route
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
management:
  endpoint:
    gateway:
      enabled: false
  endpoints:
    web:
      exposure:
        include: gateway