spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cdfive2019?autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: 123456
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 20
    packages:
      trust-all: true