spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cdfive2020?autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
    username: root
    password: 12345678
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 20
    packages:
      trust-all: true
