server:
  port: 10002

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cdfive2019?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.cdfive.support.jpa.util.UnderscoreNameCustomizer
  profiles:
    active: dev

sentinel:
  enable: true
  app-name: cdfive-log
  transport-dashboard: localhost:8080
  transport-port: 8711
  datasource-type: redis

redis:
  host: localhost
  port: 6379
  timeout-ms: 2000