server:
  port: 7777
spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
    use-read-only-response-cache: false
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

#management:
#  endpoints:
#    web:
#      exposure:
#        include: \\*
#  info:
#    env:
#      enabled: true