spring:
  profiles:
    active: dev

sentinel:
  enable: true
  app-name: cdfive-api
  transport-dashboard: localhost:8080
  transport-port: 8721
  datasource-type: redis

redis:
  host: localhost
  port: 6379
  timeout-ms: 2000