spring:
  application:
    name: cdfive-api
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
    register-with-eureka: true
    fetch-registry: true

sentinel:
  enable: true
  app-name: cdfive-api
  transport-dashboard: localhost:8080
  transport-port: 8721
  datasource-type: redis

redis:
  host: localhost
  port: 6379
  timeout-ms: 2000