server:
  port: 10003

spring:
  data:
    elasticsearch:
      clusterName: elasticsearch
      clusterNodes: localhost:9200
      username: elastic
      password: elastic
      maxConnPerRoute: 2
      maxConnTotal: 20

sentinel:
  enable: true
  app-name: cdfive-search
  transport-dashboard: localhost:8080
  transport-port: 8751
  datasource-type: redis