server:
  port: 10003

spring:
  data:
    elasticsearch:
      clusterName: elasticsearch
      clusterNodes: localhost:9200
      username: elastic
      password: elastic
      maxConnPerRoute: 2
      maxConnTotal: 20