server:
  port: 10003

spring:
  application:
    name: cdfive-search
  data:
    elasticsearch:
      clusterName: elasticsearch
      clusterNodes: localhost:9200
      username: elastic
      password: elastic
      maxConnPerRoute: 2
      maxConnTotal: 20
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 20
    packages:
      trust-all: true

sentinel:
  enable: true
  app-name: cdfive-search
  transport-dashboard: localhost:8080
  transport-port: 8751
  datasource-type: redis