server:
  port: 10003

spring:
  application:
    name: cdfive-search
  data:
    elasticsearch:
      clusterName: elasticsearch
      clusterNodes: localhost:9200
      username: elastic
      password: elastic
      maxConnPerRoute: 2
      maxConnTotal: 20
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 20
    packages:
      trust-all: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
    register-with-eureka: true
    fetch-registry: true

sentinel:
  enable: true
  app-name: cdfive-search
  transport-dashboard: localhost:8080
  transport-port: 8751
  dataSource:
    type: redis
    redis:
      host: localhost
      port: 6379
      password:

cdfive:
  framework:
    logRequest: true
    wrapApiResponse: true