spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cdfive2020?autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
    username: root
    password: 12345678

reids:
  host: localhost
  port: 6379
  timeout-ms: 2000