server:
  port: 10004

spring:
  application:
    name: cdfive-user
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.cdfive.support.jpa.util.UnderscoreNameCustomizer
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
    register-with-eureka: true
    fetch-registry: true

sentinel:
  enable: true
  appName: cdfive-user
  transport:
    dashboard: localhost:8080
    port: 8741
  dataSource:
    type: redis
    redis:
      host: localhost
      port: 6379
      password:

jwt:
  enable: true
  secret: testJwt
  expireTimeMs: 36000000

cdfive:
  framework:
    wrapApiResponse: true