server:
  port: 10004

spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.cdfive.support.jpa.util.UnderscoreNameCustomizer
  profiles:
    active: dev

sentinel:
  enable: true
  app-name: cdfive-user
  transport-dashboard: localhost:8080
  transport-port: 8741
  datasource-type: redis