package com.cdfive.learn.javabasic;

import com.cdfive.common.util.FastJsonUtil;
import com.cdfive.common.util.JacksonUtil;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import org.apache.commons.lang3.StringUtils;

/**
 * @author cdfive
 */
public class GetterSetterTest {

    public static void main(String[] args) {
        Item item = new Item("aaaa", "sss", Boolean.TRUE, false);
        // {"item":"aaaa","vSwitch":"sss","nFlag":true,"nUser":false}
        System.out.println(JacksonUtil.objToJson(item));
        // {"item":"aaaa","nFlag":true,"nUser":false,"vSwitch":"sss"}
        System.out.println(FastJsonUtil.obj2Json(item));

        System.out.println(StringUtils.center("分隔线", 50, "-"));

        LombokItem lombokItem = new LombokItem("aaaa", "sss", Boolean.TRUE, false);
        // {"item":"aaaa","nuser":false,"nflag":true,"vswitch":"sss"}
        System.out.println(JacksonUtil.objToJson(lombokItem));
        // {"item":"aaaa","nFlag":true,"nUser":false,"vSwitch":"sss"}
        System.out.println(FastJsonUtil.obj2Json(lombokItem));

        System.out.println(StringUtils.center("分隔线", 50, "-"));

        LombokItem2 lombokItem2 = new LombokItem2("aaaa", "sss", Boolean.TRUE, false);
        // {"item":"aaaa","nuser":false,"nflag":true,"vswitch":"sss","vSwitch":"sss","nFlag":true,"nUser":false}
        System.out.println(JacksonUtil.objToJson(lombokItem2));
        // {"item":"aaaa","nFlag":true,"nUser":false,"vSwitch":"sss"}
        System.out.println(FastJsonUtil.obj2Json(lombokItem2));
    }

    /**
     * getters and setters are generated by IDEA
     */
    private static class Item {

        public Item(String item, String vSwitch, Boolean nFlag, boolean nUser) {
            this.item = item;
            this.vSwitch = vSwitch;
            this.nFlag = nFlag;
            this.nUser = nUser;
        }

        private String item;

        private String vSwitch;

        private Boolean nFlag;

        private boolean nUser;

        public String getItem() {
            return item;
        }

        public void setItem(String item) {
            this.item = item;
        }

        public String getvSwitch() {
            return vSwitch;
        }

        public void setvSwitch(String vSwitch) {
            this.vSwitch = vSwitch;
        }

        public Boolean getnFlag() {
            return nFlag;
        }

        public void setnFlag(Boolean nFlag) {
            this.nFlag = nFlag;
        }

        public boolean isnUser() {
            return nUser;
        }

        public void setnUser(boolean nUser) {
            this.nUser = nUser;
        }
    }

    /**
     * getters and setters are generated by lombok
     */
    @AllArgsConstructor
    @Data
    private static class LombokItem {

        private String item;

        private String vSwitch;

        private Boolean nFlag;

        private boolean nUser;
    }

    /**
     * getters and setters are generated by lombok
     * using @JsonProperty of jackson lib
     */
    @AllArgsConstructor
    @Data
    private static class LombokItem2 {

        private String item;

        @JsonProperty("vSwitch")
        private String vSwitch;

        @JsonProperty("nFlag")
        private Boolean nFlag;

        @JsonProperty("nUser")
        private boolean nUser;
    }
}
